name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check for changes in FovChanger folder
      run: |
        CHANGED_FILES=$(curl -Ls "$GITHUB_EVENT_PATH/diff" | grep -E "^[+-]{3} b/([^[:space:]]+)" | awk '{print $2}')
        CHANGED_FOV_FILES=$(echo "$CHANGED_FILES" | grep -E "^FovChanger/")
        if [ -z "$CHANGED_FOV_FILES" ]; then
          echo "No changes were made in the FovChanger folder. Exiting."
          exit 0
        fi

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Set body text
      run: |
        if [ "${{github.event.head_commit.message}}" == "" ]; then
          echo "::set-env name=BODY_TEXT::Commit ID: ${{github.sha}}"
        else
          echo "::set-env name=BODY_TEXT::${{github.event.head_commit.message}}"
      
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "New Release!"
        body: ${{ env.BODY_TEXT }}
        files: | 
          x64/Release/FovChanger.dll